var _miftikcz_project_list = [
    [
      "MiftikWeb",
      [
        "miftik.tk",
        ";mweb;2021;otherlinks;web;"
      ]
    ],
    [
      "Miftik Army",
      [
        "https://discord.com/invite/SDxqN8qab2",
        ";discord;og;comunity;"
      ]
    ],
    [
      "Idea Keeper",
      [
        "miftikcz.github.io/idea-keeper",
        ";github.io;2022;tool;personal;web;"
      ]
    ],
    [
      "Drawing",
      [
        "miftikcz.github.io/whiteboard",
        ";github.io;2022;tool;personal;web;"
      ]
    ],
    [
      "Duck Clicker",
      [
        "miftikcz.github.io/kachna-clicker",
        ";github.io;2022;game;web;"
      ]
    ],
    [
      "Games",
      [
        "miftik.tk/fun",
        ";mweb;game;otherlinks;web;"
      ]
    ],
    [
      "Oats",
      [
        "miftikcz.github.io/vlocky",
        ";github.io;web;2022;personal;food;"
      ]
    ],
    [
      "Fast Learn",
      [
        "miftik.tk/fastLearn",
        ";mweb;2022;web;school;personal;edu;"
      ]
    ],
    [
      "Counter",
      [
        "miftik.tk/counter",
        ";mweb;2022;tool;personal;web;"
      ]
    ],
    [
      "Bot Tutorial",
      [
        "github.com/MiftikCZ/bot-tutorial",
        ";github.com;discord;2021;tutorial;personal;web;"
      ]
    ],
    [
      "MiftikRaid",
      [
        "github.com/MiftikCZ/miftikraid",
        ";github.com;discord;2021;tutorial;personal;tool;cli;"
      ]
    ],
    [
      "Webhook Spam",
      [
        "github.com/MiftikCZ/WebhookSpammer",
        ";github.com;discord;2021;tutorial;personal;web;tool;"
      ]
    ],
    [
      "Gym Help",
      [
        "miftik.tk/posilovani",
        ";mweb;gym;2022;tutorial;personal;web;"
      ]
    ],
    [
      "Gym Server",
      [
        "miftik.tk/gym",
        ";mweb;gym;2022;tutorial;personal;discord;comunity;"
      ]
    ],
    [
      "Gym Counter",
      [
        "miftikcz.github.io/sets-counter/",
        ";gym;github.io;2022;tool;personal;web;"
      ]
    ],
    [
      "MC Pack",
      [
        "www.mediafire.com/file/v5o4gmqxz7ej4ym/%25C2%25A71MiftikCZ_Pack%25C2%25A78.zip/file",
        ";custom;2021;personal;web;"
      ]
    ],
    [
      "Drinko",
      [
        "miftikcz.github.io/drinko-app/",
        ";gym;github.io;2022;tool;personal;web;"
      ]
    ],
    [
      "URL Short",
      [
        "c.miftik.tk",
        ";mweb;2022;tool;personal;web;"
      ]
    ],
    [
      "Shortcuts",
      [
        "miftikcz.github.io/MiftikCZ/html-shortcuts",
        ";github.io;2022;tool;personal;web;"
      ]
    ],
    [
      "Startpage",
      [
        "miftikcz.github.io/homepage",
        ";github.io;2022;custom;personal;web;"
      ]
    ],
    [
      "Startpage 2",
      [
        "miftikcz.github.io/startpage-2",
        ";github.io;2023;custom;personal;web;"
      ]
    ],
    [
      "Pinguin",
      [
        "github.com/MiftikCZ/pinguin",
        ";github.com;2023;tool;personal;cli;"
      ]
    ],
    [
      "EdLinkMe",
      [
        "edlinkme.miftik.tk/",
        ";mweb;2021;tool;personal;web;"
      ]
    ],
    [
      "Image Manager",
      [
        "https://replit.com/@MiftikCZ/Image-Manager",
        ";replit;2021;tool;personal;web;"
      ]
    ],
    [
      "Token Checker",
      [
        "https://replit.com/@MiftikCZ/TokensChecker#index.html",
        ";replit;2021;tool;personal;web;"
      ]
    ],
    [
      "Web Unblocker",
      [
        "miftik.tk/ub/",
        ";mweb;2022;school;tool;personal;web;"
      ]
    ],
    [
      "Notes",
      [
        "miftik.tk/notepad/",
        ";mweb;2022;tool;personal;web;"
      ]
    ],
    [
      "Dirty Script",
      [
        "github.com/MiftikCZ/dirty-script",
        ";github.com;2022;tool;dev;"
      ]
    ],
    [
      "Pattern",
      [
        "github.com/MiftikCZ/kresleniPattern",
        ";github.com;2022;math;personal;web;"
      ]
    ]
  ]
